// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vsagblcnmzoknvmvriyf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZzYWdibGNubXpva252bXZyaXlmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyNzcwNjYsImV4cCI6MjA3Mzg1MzA2Nn0.qw8F8inmx8CZDXLidjUydV0Hn7AwLQgEZWvGwqF4zus";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});